# Production TACC Configuration Profile
# Optimized settings for production runs and publications

# Core Physics Settings
microlaw: ppn
microlaw_params: {}

bn_family: exponential  
bn_params:
  kappa: 2.0

# Fitment Configuration
fitment:
  name: no_fit  # Production typically uses pre-fitted parameters
  params: {}

# Experiment Settings
experiment:
  output_dir: production_results
  save_plots: true
  plot_format: pdf  # High quality for publications
  plot_dpi: 300     # High DPI for publications

# Advanced Settings
advanced:
  enable_validation: true
  enable_stamping: true   # Critical for reproducibility
  seed_strategy: parameter_dependent

# Notebook Settings  
notebook:
  show_chooser_widgets: false  # Clean interface for production
  auto_display_components: false
  widget_style: compact
