name: exp_bandgaps_v1
mechanism: bandgaps         # bandgaps | causal_diamond | mode_crowding
time_mode: emergent         # emergent | explicit (not used yet; log only)
hidden_dims: 0              # micro DoF only; macro remains 3+1
data:
  dof_table: data/thermo_runs/bandgaps_run_v1.csv
fit:
  dof_law: exponential      # fit DoF(N)=exp[-a*(1-N)]
  map_beta_rule: power      # psi = DoF^beta
freeze:
  out_kappa: data/derived/kappa.json
validation:
  ppn: true
  bending: { b_over_rs: [10, 20, 50, 100] }
  shapiro: { impact_b_over_rs: 10 }
  perihelion: { a_AU: 0.387, e: 0.206 }   # Mercury
report:
  baselines: [polynomial, exponential, power]
  seed: 42
